### ISSUE TITLE
While installing CLI quote, Bitdefender throws a virus detected error

### ISSUE THREAD

**Issue by chappcc** [markcheno/go-quote#19]
I tried to install CLI quote running `go install github.com/markcheno/go-quote/quote` and Bitdefender throws the following error:
"The file C:\Users\XXXXX\AppData\Local\Temp\go-build3256829184\b001\exe\a.out.exe is infected with Gen:Variant.Bulz.368851"
and the install is not allowed to execute since Bitdefender denies access to the file.

**Comment by markcheno** [comment]
Very strange. That is the first I have heard about a problem like that. I am not familiar with Bitdefender, so have no idea what can be done about it, if anything.

**Comment by chappcc** [comment]
I’m thinking there must be some part of the code that looks like something in Bitdefender's virus table.  I’ve tried the download a couple of time with the same result.
