### ISSUE TITLE
No data from quote.NewQuoteFromGoogle()

### ISSUE THREAD

**Issue by chappcc** [markcheno/go-quote#20]
I am getting no data when I try to access data from Google.  Data from Yahoo are accessed without issue.  Here are the codes for each.

Yahoo  
`stock, err := quote.NewQuoteFromYahoo(tickerstr, todayb, today, quote.Daily, true)`

Google  
`stock, err := quote.NewQuoteFromGoogle(tickerstr, todayb, today, quote.Daily)`

My dates
```
currentTime := time.Now()
previousdays := 60
previousTime := currentTime.AddDate(0, 0, -previousdays)
today := currentTime.Format(layoutISO)
todayb := previousTime.Format(layoutISO)
```

**Comment by markcheno** [comment]
I can confirm the Google source no longer works. They must have changed something on their end. I will attempt to fix when I get a chance.

**Comment by chappcc** [comment]
Thanks for the reply.  I am having good success with Yahoo; however, it misses some of the preferred shares Googlefinance picks up.  Also, I’d like to compare the accuracy of their data.

**Comment by markcheno** [comment]
I did a quick search and it seems Google has shut down the api. There are many other projects with the same situation.
