### ISSUE TITLE
Running quote CLI command on Pi 3 returns word in quotes

### ISSUE THREAD

**Issue by ionicbond** [markcheno/go-quote#6]
Hi, I've downloaded the quote package and installed it on my Pi 3.  The OS is "Raspbian GNU/Linux 8 (jessie)" and the go version is go version go1.10.2 linux/arm.  I can run other go applications, for instance the "Hello World" app from petergloor.  However, when I try to run the quote application by running quote etf or quote spy from the CLI, what I get is 'etf' or 'spy' returned respectively.  The quote application seems to be conflicting with the built in quote os apllication.  Am I missing something?  Let me know, thanks!

**Comment by ionicbond** [comment]
I just did some research and the quote command is an internal command to some linux system.  when i type in "type quote" at the command line i get the below:

pi@billboard:~ $ type quote
quote is a function
quote ()
{
    local quoted=${1//\'/\'\\\'\'};
    printf "'%s'" "$quoted"
}
pi@billboard:~ $

Hope this helps you understand the issue I'm having running your code

**Comment by markcheno** [comment]
Yes, unfortunately there is a built-in "quote" function in the shell on some linux systems. 
My solution has been to add the command "unset quote" in ~/.bashrc or ~/.profile
That will temporarily remove the function from your shell at login time. I've never seen any adverse effects from doing that. You can also run quote by supplying the path: $GOPATH/bin/quote or create an alias. I hope that helps.

**Comment by ionicbond** [comment]
Hi Mark and thanks for that info.  I'll try that out when I get a chance this week. Cheers!
